# Generated by Django 2.2a1 on 2019-02-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveSmallIntegerField()),
                ('cups', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mocca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_powered', models.BooleanField()),
                ('started_brewing', models.DateTimeField(verbose_name='started brewing')),
                ('lost_power', models.BooleanField()),
                ('outages', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time pulled')),
                ('coffee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee')),
                ('mocca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffee.Mocca')),
            ],
        ),
    ]
