# Generated by Django 2.2a1 on 2019-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveIntegerField()),
                ('cups', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('is_powered', models.BooleanField()),
                ('started_brewing', models.DateTimeField(verbose_name='started brewing')),
                ('lost_power', models.BooleanField()),
                ('outages', models.DateTimeField()),
                ('time', models.DateTimeField(verbose_name='time pulled')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
