# Generated by Django 2.2a1 on 2019-02-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mocca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_powered', models.BooleanField()),
                ('started_brewing', models.DateTimeField(verbose_name='started brewing')),
                ('lost_power', models.BooleanField()),
                ('outages', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='is_powered',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='lost_power',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='outages',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='started_brewing',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='time',
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time pulled')),
                ('coffee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffee.Coffee')),
                ('mocca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffee.Mocca')),
            ],
        ),
    ]
